In [1]:
import pandas

In [2]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [3]:
%ls

 Volume in drive C is Windows
 Volume Serial Number is 3AD7-CDBE

 Directory of C:\Users\Yash\Desktop

18-06-2022  21:20    <DIR>          .
25-04-2022  20:16    <DIR>          ..
16-06-2022  21:33    <DIR>          .ipynb_checkpoints
28-07-2021  21:47    <DIR>          cp
18-06-2022  21:20         1,416,164 data science.ipynb
               1 File(s)      1,416,164 bytes
               4 Dir(s)  100,425,760,768 bytes free


In [4]:
%%HTML
<h1>this is a heading</h1>

In [5]:
%matplotlib inline

In [6]:
%timeit print("yassh")

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yassh
yass

In [7]:
list1 = [3,4,5]
print(list1)

[3, 4, 5]


In [8]:
import numpy as np

In [9]:
l1 = [3,4,5,6]

In [10]:
arr = np.arange(1000000)

In [11]:
pythlist = list(range(1000000))

In [12]:
%time for _ in range(10): [item *3 for item in pythlist]

Wall time: 849 ms


In [13]:
%time for _ in range(10): arr = arr*3

Wall time: 24 ms


In [14]:
np.array([3,4,5,6,7,8,9])

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
array1 = np.array([3,2,4,5,7,0])

In [16]:
print(type(array1))

<class 'numpy.ndarray'>


In [17]:
print(array1)

[3 2 4 5 7 0]


In [18]:
array1.shape  

(6,)

In [19]:
array1.dtype

dtype('int32')

In [20]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones(6).dtype

dtype('float64')

In [22]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
#np.zeroes gives zeros while np.empty can give garbage valeues

In [24]:
array1*array1

array([ 9,  4, 16, 25, 49,  0])

In [25]:
array1+array1

array([ 6,  4,  8, 10, 14,  0])

In [26]:
array1-array1

array([0, 0, 0, 0, 0, 0])

In [27]:
array1/array1

C:\Users\Yash\AppData\Local\Temp/ipykernel_16708/3963778006.py:1: RuntimeWarning: invalid value encountered in true_divide
  array1/array1


array([ 1.,  1.,  1.,  1.,  1., nan])

In [28]:
array1**array1

array([    27,      4,    256,   3125, 823543,      1], dtype=int32)

##slicing

In [29]:
array2 = np.array([5,45,4,6,7,8])

In [30]:
arr=array2[4:6]

In [31]:
arr

array([7, 8])

more on numpy functions

In [32]:
ar1 = np.array([[1,2,3],
                [4,5,6]])

In [33]:
ar1.sum(axis=0)

array([5, 7, 9])

In [34]:
ar1.sum(axis=1)

array([ 6, 15])

In [35]:
ar2 = np.array([[7,8,9],
                [2,8,0]])

In [36]:
ar1.dot(ar2.transpose())

array([[ 50,  18],
       [122,  48]])

In [37]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [38]:
len(dir(np))

608

In [39]:
np.cross(ar1,ar2)

array([[ -6,  12,  -6],
       [-48,  12,  22]])

In [40]:
np.sort(ar1)

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
%%time
np.sort(ar1,axis=0,kind='mergesort')

Wall time: 999 µs


array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
 %%time
np.sort(ar1,axis=0,kind='heapsort')

Wall time: 0 ns


array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
a=np.arange(6)

In [44]:
a

array([0, 1, 2, 3, 4, 5])

In [56]:
b = np.array([1,2,3,4,5,9,7,8,23,345,56,34])
b=b.reshape(3,4)

In [57]:
b

array([[  1,   2,   3,   4],
       [  5,   9,   7,   8],
       [ 23, 345,  56,  34]])

In [58]:
np.argsort(b)

array([[0, 1, 2, 3],
       [0, 2, 3, 1],
       [0, 3, 2, 1]], dtype=int64)

In [59]:
np.argmin(b)

0

In [60]:
np.argmax(b)

9