** Welcome to numpy tutorial**

In [6]:
import numpy as np

In [24]:
myarr = np.array([[3,6,32,7]])

In [12]:
myarr[0,1]

6

In [13]:
myarr.shape

(1, 4)

In [17]:
myarr.dtype

dtype('int32')

In [26]:
zeroes = np.zeroes((2,5))

AttributeError: module 'numpy' has no attribute 'zeroes'

In [25]:
zeroes

NameError: name 'zeroes' is not defined

In [27]:
rng = np.arange(15)

In [28]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
lspace = np.linspace(1,5,12)

In [31]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [32]:
emp = np.empty((4,6))

In [33]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.69118787e-306, 1.42417900e-306, 1.78019082e-306],
       [1.37961913e-306, 6.23057349e-307, 1.02360935e-306,
        1.69120416e-306, 1.78022342e-306, 6.23058028e-307],
       [1.06811422e-306, 1.39071445e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
       [1.33510679e-306, 2.22522597e-306, 1.11260144e-306,
        6.89812281e-307, 2.22522596e-306, 2.56765117e-312]])

In [34]:
emp_like = np.empty_like(lspace)

In [35]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [36]:
ide = np.identity(45)

In [37]:
ide.shape

(45, 45)

In [38]:
arr = np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr = arr.reshape(3,33)

In [45]:
arr = arr.ravel()

In [46]:
arr.shape

(99,)

In [47]:
x= [[1,2,3], [4,5,6], [7,1,0]]

In [48]:
ar = np.array(x)

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.sum(axis=0)

array([12,  8,  9])

In [52]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [53]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [54]:
ar.flat

In [55]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [57]:
ar.ndim

2

In [58]:
ar.size

9

In [60]:
ar.nbytes

36

In [61]:
one = np.array([1,3,4,634,2])

In [62]:
one.argmax()

3

In [63]:
one.argmin()

0

In [64]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [66]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [67]:
ar.argmin()

8

In [68]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [70]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [71]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [73]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [74]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
ar2

NameError: name 'ar2' is not defined

In [77]:
ar2 = np.array([[1,2,1],
              [4,0,6],
              [8,1,0]])

In [78]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [79]:
[324,34]+[34,546]

[324, 34, 34, 546]

In [80]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [81]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [82]:
ar.sum()

29

In [83]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [84]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [85]:
np.count_nonzero(ar)

8

In [86]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [87]:
 import sys

In [88]:
py_ar = [0,4,55,2]

In [89]:
np_ar = np.array(py_ar)

In [90]:
sys.getsizeof(1)*len(py_ar)

112

In [91]:
np_ar.itemsize * np_ar.size

16