In [2]:
import numpy as np
a = np.arange(9)
print('The original array')
print(a)

print()

b=a.reshape(3,3)
print("The modified array:")
print(b)

The original array
[0 1 2 3 4 5 6 7 8]

The modified array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [3]:
print(b.flatten())

[0 1 2 3 4 5 6 7 8]


In [4]:
b.flatten(order="F")

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [5]:
a= np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [6]:
np.transpose(a)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [7]:
b=np.arange(8).reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
c = b.reshape(2,2,2)
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
np.rollaxis(c,2,1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [12]:
np.swapaxes(c,1,2)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

# Numpy Arithmetic Operations

In [13]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
b = np.array([10,10,10])
b

array([10, 10, 10])

In [15]:
np.add(a,b)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [16]:
np.subtract(a,b)

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [17]:
np.multiply(a,b)

array([[ 0, 10, 20],
       [30, 40, 50],
       [60, 70, 80]])

In [18]:
np.divide(a,b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

# slicing

In [19]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
a[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [21]:
a[:4]

array([0, 1, 2, 3])

In [22]:
a[5]

5

In [27]:
s = slice(2,90,2)
a[s]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# Iterating Over Array

In [30]:
a = np.arange(0,45,5)
a = a.reshape(3,3)
a


array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [31]:
for x in np.nditer(a):
    print(x)

0
5
10
15
20
25
30
35
40


#Iteration order(c-style and f-style)

#Iteration order(c-style and f-style)

# Iteration order(c-style and f-style)

In [33]:
print(a)
for x in np.nditer(a, order="C"):
    print(x)
    
for x in np.nditer(a, order="F"):
    print(x)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]]
0
5
10
15
20
25
30
35
40
0
15
30
5
20
35
10
25
40


# Joining Arrays

In [ ]:
a = np.array([1,2],[3,4])
print("first array")
print(a)
b = np.array([[5,6],[7,8]])
print("second array")
print(b)
